# Generated by Django 2.1.5 on 2019-02-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Widget', '0003_auto_20190203_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Widget.Widget', to_field='widget'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
